### PR TITLE
Remove CalendarLib dependency

### LINKED ISSUE #73: Dependency on calendar breaks usage with mirage
We are using `webmachine` in a `mirage` unikernel, and version 0.4.0 contains a dependency on `calendar` which breaks xen builds:

```
Error: No implementations provided for the following modules:
         Str referenced from /home/svanders/.opam/4.04.1/lib/calendar/calendarLib.cmxa(CalendarLib)
         Unix referenced from /home/svanders/.opam/4.04.1/lib/calendar/calendarLib.cmxa(CalendarLib)
```
Installed package versions are:
```
$ opam list
# Installed packages for 4.04.1:
asn1-combinators               0.1.3  Define ASN.1 grammars in OCaml
astring                        0.8.3  Alternative String module for OCaml
base                          v0.9.2  Full standard library replacement for OCam
base-bigarray                   base  Bigarray library distributed with the OCam
base-bytes                      base  Bytes library distributed with the OCaml c
base-threads                    base  Threads library distributed with the OCaml
base-unix                       base  Unix library distributed with the OCaml co
base64                         2.1.2  For OCaml
biniou                        1.0.13  Binary data format designed for speed, saf
bos                            0.1.6  Basic OS interaction for OCaml
calendar                      2.03.2  Library for handling dates and times in yo
camlp4                        4.04+1  Camlp4 is a system for writing extensible 
cmdliner                       1.0.0  Declarative definition of command line int
cohttp                        0.22.0  HTTP(S) library for Lwt, Async and Mirage
conduit                       0.15.3  Network connection library for TCP and SSL
conf-gmp                           1  Virtual package relying on a GMP lib syste
conf-m4                            1  Virtual package relying on m4
conf-perl                          1  Virtual package relying on perl
conf-pkg-config                  1.0  Virtual package relying on pkg-config inst
conf-which                         1  Virtual package relying on which
cppo                           1.5.0  Equivalent of the C preprocessor for OCaml
cpuid                          0.1.1  Detect CPU features
crunch                         2.0.0  Convert a filesystem into a static OCaml m
cstruct                        2.4.1  access C structures via a camlp4 extension
depext                         1.0.4  Query and install external dependencies of
dispatch                       0.3.0  Path-based dispatching for client- and ser
dns                           0.20.0  DNS client and server implementation
duration                       0.1.0  Conversions to various time units
easy-format                    1.2.0  High-level and functional interface to the
fieldslib                     v0.9.0  Syntax extension to define first class val
fmt                            0.8.3  OCaml Format pretty-printer combinators
fpath                          0.7.2  File system paths for OCaml
functoria                      2.0.2  A DSL to organize functor applications.
functoria-runtime              2.0.0  
gmp-xen                        6.0.0  The GNU Multiple Precision Arithmetic Libr
hashcons                       1.0.1  OCaml hash-consing library
io-page                        1.6.1  Allocate memory pages suitable for aligned
ipaddr                         2.7.2  IP (and MAC) address manipulation
jbuilder                   1.0+beta8  Fast, portable and opinionated build syste
logs                           0.6.2  Logging infrastructure for OCaml
lwt                            2.7.1  Monadic promises and concurrent I/O
magic-mime                     1.0.0  Convert file extensions to MIME types
minios-xen                       0.9  A minimal OS for running under the Xen hyp
mirage                         3.0.2  The MirageOS library operating system
mirage-block                   1.0.0  Utilities and module definitions for deali
mirage-block-lwt               1.0.0  Utilities and module definitions for deali
mirage-bootvar-xen             0.4.0  Library for reading MirageOS unikernel boo
mirage-channel                 3.0.0  MirageOS channels
mirage-channel-lwt             3.0.0  MirageOS channels
mirage-clock                   1.2.0  Libraries and module types for two kinds o
mirage-clock-freestanding      1.2.0  
mirage-clock-lwt               1.2.0  Libraries and module types for two kinds o
mirage-conduit                 2.3.1  Virtual package for the MirageOS Conduit t
mirage-console                 2.2.0  A Mirage-compatible Console library for Xe
mirage-console-lwt             2.2.0  A Mirage-compatible Console library for Xe
mirage-console-xen             2.2.0  A Mirage-compatible Console library for Xe
mirage-console-xen-proto       2.2.0  Protocol for communicating with Xen consol
mirage-device                  1.0.0  Foundational module types for devices.
mirage-dns                     2.7.0  Virtual package for the MirageOS DNS trans
mirage-entropy                 0.4.0  Entropy source for MirageOS unikernels.
mirage-flow                    1.2.0  Various implementations of the MirageOS FL
mirage-flow-lwt                1.2.0  Various implementations of the MirageOS FL
mirage-fs                      1.0.0  MirageOS filesystem utilities
mirage-fs-lwt                  1.0.0  Module type definitions for filesystems, w
mirage-http                    3.1.0  MirageOS-compatible implementation of the 
mirage-kv                      1.0.0  MirageOS utilities for interfacing with ke
mirage-kv-lwt                  1.0.0  MirageOS utilities for interfacing with ke
mirage-logs                    0.3.0  A reporter for the Logs library that write
mirage-net                     1.0.0  MirageOS TCP/IP networking library
mirage-net-lwt                 1.0.0  MirageOS TCP/IP networking library
mirage-net-xen                 1.7.0  Ethernet network device driver for MirageO
mirage-no-solo5                    1  Virtual package conflicting with mirage-so
mirage-os-shim                 3.0.0  Portable shim for MirageOS APIs
mirage-profile                 0.7.0  Collect profiling information
mirage-protocols               1.1.0  Module type definitions for network protoc
mirage-protocols-lwt           1.1.0  
mirage-random                  1.0.0  Random signatures for MirageOS, and an imp
mirage-runtime                 3.0.0  A bundle of useful runtime functions for a
mirage-stack                   1.0.0  Module type definitions for network stacks
mirage-stack-lwt               1.0.0  Module type definitions for network stacks
mirage-time                    1.0.0  Module type definitions for dealing with t
mirage-time-lwt                1.0.0  Module type definitions for dealing with t
mirage-types                   3.0.0  Module type definitions for Mirage-compati
mirage-types-lwt               3.0.0  Lwt module type definitions for Mirage-com
mirage-xen                     3.0.0  MirageOS library for Xen compilation
mirage-xen-minios              0.8.0  Xen MiniOS guest operating system library
mirage-xen-ocaml               3.0.0  MirageOS headers for the OCaml runtime
mirage-xen-posix               2.6.0  MirageOS library for posix headers
nocrypto                       0.5.4  Simpler crypto
oasis                          0.4.8  Tooling for building OCaml libraries and a
ocaml-compiler-libs           v0.9.0  OCaml compiler libraries repackaged
ocaml-migrate-parsetree          1.0  Convert OCaml parsetrees between different
ocaml-src                     4.04.0  Compiler sources
ocamlbuild                    0.11.0  OCamlbuild is a build system with builtin 
ocamlfind                      1.7.1  A library manager for OCaml
ocamlgraph                     1.8.7  A generic graph library for OCaml
ocamlify                       0.0.1  Include files in OCaml code
ocamlmod                       0.0.8  Generate OCaml modules from source files
ocb-stubblr                    0.1.1  OCamlbuild plugin for C stubs
ocplib-endian                    1.0  Optimised functions to read and write int1
ounit                          2.0.0  Unit testing framework loosely based on HU
parse-argv                     0.0.3  process strings into sets of command-line 
ppx_ast                       v0.9.1  OCaml AST used by Jane Street ppx rewriter
ppx_core                      v0.9.0  Standard library for ppx rewriters
ppx_deriving                     4.1  Type-driven code generation for OCaml >=4.
ppx_driver                    v0.9.1  Feature-full driver for OCaml AST transfor
ppx_fields_conv               v0.9.0  Generation of accessor and iteration funct
ppx_metaquot                  v0.9.0  Write OCaml AST fragment using OCaml synta
ppx_optcomp                   v0.9.0  Optional compilation for OCaml
ppx_sexp_conv                 v0.9.0  Generation of S-expression conversion func
ppx_tools                        5.0  Tools for authors of ppx rewriters and oth
ppx_tools_versioned            5.0.1  A variant of ppx_tools based on ocaml-migr
ppx_traverse_builtins         v0.9.0  Builtins for Ppx_traverse
ppx_type_conv                 v0.9.0  Support Library for type-driven code gener
ptime                          0.8.3  POSIX time for OCaml
randomconv                     0.1.0  Convert from random bytes to random native
re                             1.7.1  RE is a regular expression library for OCa
result                           1.2  Compatibility Result module
rresult                        0.5.0  Result value combinators for OCaml
sexplib                       v0.9.1  Library for serializing OCaml values to an
shared-memory-ring             1.3.0  Shared memory rings for RPC and bytestream
stdio                         v0.9.0  Standard IO library for OCaml
stringext                      1.4.3  Extra string functions for OCaml
tcpip                          3.1.0  Userlevel TCP/IP stack
tls                            0.8.0  Transport Layer Security purely in OCaml
topkg                          0.9.0  The transitory OCaml software packager
uchar                          0.0.1  Compatibility library for OCaml's Uchar mo
uri                            1.9.2  RFC3986 URI/URL parsing library
webmachine                     0.4.0  A REST toolkit for OCaml
x509                           0.5.3  X.509 certificate (RFC5280) library
xen-evtchn                     1.0.7  Xen event channel bindings.
xen-gnt                        2.2.3  Xen grant table bindings
xenstore                       1.3.0  Xenstore protocol clients and server
yojson                         1.3.3  Yojson is an optimized parsing and printin
zarith                           1.4  Implements arithmetic and logical operatio
zarith-xen                       1.4  Implements arithmetic and logical operatio
```

### LINKED ISSUE #79: Implement parser for HTTP date format
See the specification in [RFC7231§7.1.1.1](https://tools.ietf.org/html/rfc7231#section-7.1.1.1). [Angstrom](https://github.com/inhabitedtype/angstrom) may help in this effort, or maybe something hand-rolled would work just as well.

### PR DESCRIPTION
**Pull request by ansiwen**
For timestamp processing in HTTP headers so far the calendar module
has been used, which depends on unix.  This change implements a
simple RFC1123/RFC5322 parser and allows different clock sources to
be used.  Therefore a CLOCK module must be defined, that contains a
function "now" that returns the current time as a Ptime.t value.  The
Make functor now takes an additional Clock parameter for this module.
Examples for POSIX or MirageOS clocks are provided.

Closes #73
Closes #79

### CODE REVIEW

**Comment by ansiwen** [comment]
@seliopou, what do you think?

**Comment by seliopou** [comment]
Sorry for taking so long to get to this. I'll take a look today when I catch a few free minutes.

File: _oasis [hunk 1]
```diff
@@ -22,7 +22,7 @@ Flag examples
 Library webmachine
   Path:             lib
   BuildDepends:
-    calendar        (>= 2.03.2),
+    ptime           (>= 0.8.0),
```
Comment (seliopou) [inline _oasis]: Ykes, this Oasis file shouldn't be here any more. Dependencies should be updated in the OPAM file and jbuild file, which it looks like you've done.

I'll send a separate PR to delete this file. Can you revert the change?

Comment (seliopou) [reply _oasis]: This actually got removed in #85.

File: lib/wm_util.ml [hunk 2]
```diff
@@ -111,11 +111,71 @@ module MediaType = struct
     loop ranges
 end
 
-module Date = struct
-  open CalendarLib
+module type Date_sig = sig
```
Comment (seliopou) [inline lib/wm_util.ml]: `Date_sig` -> `Date`. Signatures and modules have different namespaces, so there's no chance they'll conflict.

**Comment by ansiwen** [comment]
@seliopou: ok, great! @yomimono already pointed out, that I got the uper-/lower-case naming for modules and module-types mixed up, so I would fix that anyway. but I'm waiting for your comments first to do everything in one run.

File: lib/webmachine.mli [hunk 3]
```diff
@@ -312,5 +312,5 @@ module type S = sig
         {[([`Lit, "user"; `Var "id"], `Prefix, user_resource)]} *)
 end
 
-module Make(IO:IO) : S
+module Make(IO:IO)(DATE:Wm_util.Date_sig) : S
```
Comment (seliopou) [inline lib/webmachine.mli]: I'm pretty sure `Wm_util` isn't an exposed module, so the signature should be defined in this file and then just used below. That's what's done for `IO` as well, at the top of the file.

File: lib/wm_util.ml [hunk 4]
```diff
@@ -111,11 +111,71 @@ module MediaType = struct
...
+  type t
+  val now : unit -> t
+  val parse_rfc1123_date_exn : string -> t
+  val parse_rfc1123_date : string -> t option
+end
+
+module type PtimeNow_sig = sig
```
Comment (seliopou) [inline lib/wm_util.ml]: Same as above, no need for the `_sig` suffix.

File: lib/wm_util.ml [hunk 5]
```diff
@@ -111,11 +111,71 @@ module MediaType = struct
...
+
+    module DatePtimeClock = Wm_util.MakePtimeDate(struct
+      let now = Ptime_clock.now
+    end)
+
+    module DateMirage = Wm_util.MakePtimeDate(struct
+      let now = fun () -> Ptime.v @@ Pclock.now_d_ps clock
+    end)
+*)
+module MakePtimeDate(NOW:PtimeNow_sig) : Date_sig = struct
```
Comment (seliopou) [inline lib/wm_util.ml]: I don't think this functor is necessary. since all it does is define a few functions that don't use the argument to the functor, and then it just re-exports the single functions that was provided in the argument. This suggests that the argument to `Webmachine.Make` should just be `PtimeNow_sig`, appropriately renamed.

File: lib/wm_util.ml [hunk 6]
```diff
@@ -111,11 +111,71 @@ module MediaType = struct
...
+
+  type t = Ptime.t
+
+  let now = NOW.now
 
   let parse_rfc1123_date_exn s =
```
Comment (seliopou) [inline lib/wm_util.ml]: Cool! I will have to look at the HTTP spec, but I think only `GMT` is allowed as a timezone. I guess there's no harm in supporting the others though?

File: lib/webmachine.ml [hunk 7]
```diff
@@ -710,7 +710,7 @@ module Make(IO:IO) = struct
         >>~ fun l_mod ->
         match (u_mod, l_mod) with
         | (Some u_mod', Some l_mod') ->
-           (match (Util.Date.parse_rfc1123_date_exn l_mod') > (Util.Date.parse_rfc1123_date_exn u_mod') with
+           (match (DATE.parse_rfc1123_date_exn l_mod') > (DATE.parse_rfc1123_date_exn u_mod') with
```
Comment (seliopou) [inline lib/webmachine.ml]: Should this be `Ptime.compare x y > 0`?

File: lib/webmachine.ml [hunk 8]
```diff
@@ -827,7 +827,7 @@ module Make(IO:IO) = struct
         >>~ fun l_mod ->
             match (u_mod, l_mod) with
             | (Some l_mod', Some u_mod') ->
-               (match (Util.Date.parse_rfc1123_date_exn l_mod') > (Util.Date.parse_rfc1123_date_exn u_mod') with
+               (match (DATE.parse_rfc1123_date_exn l_mod') > (DATE.parse_rfc1123_date_exn u_mod') with
```
Comment (seliopou) [inline lib/webmachine.ml]: Should this be `Ptime.compare x y > 0`?

File: lib_test/test_logic.ml [hunk 9]
```diff
@@ -41,21 +41,13 @@ module Id = struct
 
 end
 
+module DateMock = Wm_util.MakePtimeDate(struct
+  let now = fun () -> Ptime.v (17591, 0L)
```
Comment (seliopou) [inline lib_test/test_logic.ml]: Any significance to the constant chosen which should be noted?

**Comment by seliopou** [comment]
Oh, you may want to rebase to pick up changes from #85.

File: lib/wm_util.ml (hunk 2 above)
Comment (ansiwen) [reply lib/wm_util.ml]: Well, they constantly conflict in my brain. That's why I prefer the explicit style. It makes it more readable. But of course I will adapt to any style you prefer.

File: lib/webmachine.mli (hunk 3 above)
Comment (ansiwen) [reply lib/webmachine.mli]: Not sure what you mean. It _does_ work, if that's what you doubt. Or is that a style question?

File: lib/wm_util.ml (hunk 5 above)
Comment (ansiwen) [reply lib/wm_util.ml]: But that would force Ptime to be used. My current design would also allow to create webmachine without Ptime, but another time representation instead.

File: lib/wm_util.ml (hunk 6 above)
Comment (ansiwen) [reply lib/wm_util.ml]: No, the others are also allowed, but deprecated.

File: lib/webmachine.mli (hunk 3 above)
Comment (seliopou) [reply lib/webmachine.mli]: `Webmachine.Wm_util.Date_sig` would not be available to users of the library. So anybody that wanted to use that signature wouldn't be able to get a handle on it. Also, it's not clear what that signature _is_ from the `.mli`, so that folks can easily implement a module that satisfies it.

File: lib_test/test_logic.ml (hunk 9 above)
Comment (ansiwen) [reply lib_test/test_logic.ml]: nope, it was just the current time of writing the test. :-)

**Comment by ansiwen** [comment]
@seliopou Sure, I'll rebase it.

File: lib/wm_util.ml (hunk 5 above)
Comment (seliopou) [reply lib/wm_util.ml]: Ah, because it's abstract. Maybe a simpler thing to do is to just fix the type to be an `int` which specifies the number of seconds since the UNIX epoch. Any further granularity isn't useful for this use-case anyway.

File: lib/webmachine.ml (hunk 8 above)
Comment (seliopou) [reply lib/webmachine.ml]: Or rather, `DATE.compare`. It's probably error-prone to rely on polymoprhic compare for a user-provided abstract type.

File: lib/webmachine.mli (hunk 3 above)
Comment (ansiwen) [reply lib/webmachine.mli]: Wm_util doesn't have an mli file, so in my understanding it _is_ available. Or do other restriction apply here?

Here I ported irmin-http to the new webmachine, and it works: https://github.com/ansiwen/irmin/commit/e1af324883d393928755647bd07f59e07715284e 

But nevertheless, I agree that it's not beautiful. I would also prefer to hide Wm_util from the outside world. But then the whole functor has to go into webmachine.mli, if I'm not mistaken?

Comment (seliopou) [reply lib/webmachine.mli]: Got it, I thought that `Wm_util` wasn't exposed but it is. That's an error and should be fixed in a separate issue (not your problem but I suppose relevant to this feature). Ideally, only the signature would be available in the `.mli` and there would be no need for a functor. (Providing functors to create modules to pass to functors is a recipe for a headache). One way to achieve that is to make the type in the signature concrete. In my comment below I essentially suggested changing the time of now to `unit -> int` where the return value is seconds since UNIX epoch. That would achieve it, and also lead to a simple implementation for UNIX backends:

```ocaml
let now () = int_of_float (Unix.gettimeofday ())
```

File: lib/wm_util.ml [hunk 10]
```diff
@@ -111,11 +111,71 @@ module MediaType = struct
...
+          | "" | "Z" | "GMT" | "UTC" | "UT" -> 0
+          | "PST" -> -480
+          | "MST" | "PDT" -> -420
+          | "CST" | "MDT" -> -360
+          | "EST" | "CDT" -> -300
+          | "EDT" -> -240
+          | s -> Scanf.sscanf s "%c%02d%_[:]%02d" (fun sign hour min ->
+              min + hour * (if sign = '-' then -60 else 60))
+        in
+        let mon = List.assoc mon months in
```
Comment (hcarty) [inline lib/wm_util.ml]: Is the potential `Not_found` exception caught anywhere?  Or is it ok if it leaks from here?

**Comment by ansiwen** [comment]
@seliopou: So, I decided to stick with Ptime.t as the type, because the parse_rfc1123_date implementation depends on it anyway, so it doesn't really make sense to make the implementation more complicated for having int as the type. If someone really needs an int source, it's easy to convert to Ptime.t.

**Comment by seliopou** [comment]
This issue with that is that the clock interface won't be self-contained. By that I mean, in order to use the clock interface, a user must know about another library besides webmachine. A user won't be able to just look at the the signature and documentation and come up with their own implementation. They'll have to learn another library's interface and construct a value with it, even though they can easily reach for the number of seconds since epoch.

This will be the case of any UNIX-based implementation, and even the [mirage-clock](https://github.com/mirage/mirage-clock/blob/master/src/mirage_clock.ml#L30-L34) doesn't even use the `Ptime.t` type, even though it's clearly meant to interoperate with it. So it may require a change to the implementation (a small one that I can perform if you don't feel like doing it) in exchange for an easier to use interface.

**Comment by hannesm** [comment]
FWIW, the Mirage_clock changes were discussed in https://github.com/mirage/mirage/issues/442, and yes, they don't have a `ptime` dependency

**Comment by ansiwen** [comment]
@seliopou, I think the usage of Ptime.t is pretty self-explanatory, especially with the examples that I provide. And no one would ever use `(Ptime.of_float_s Unix.gettimeofday)` if you can write `Ptime_clock.now` instead as in the example. As I said, we have the Ptime dependency anyway. But if you insist, I will prepare an int interface. :smirk:

**Comment by seliopou** [comment]
That'd be great, thanks.

**Comment by ansiwen** [comment]
@seliopou done

**Comment by ansiwen** [comment]
rebased...

**Comment by seliopou** [comment]
Thanks!
